{
 "title": "Telegraf metrics 1",
 "description": "InfluxDB dashboards for telegraf metrics",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "SUMMARY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "repeat": "server",
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "measurement": "system_uptime",
       "query": "SELECT last(\"uptime\") AS \"value\" FROM \"system\" WHERE  $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk space",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "repeat": "server",
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "query": "SELECT mean(\"free\") AS \"value\" FROM \"disk\" WHERE \"path\" = '/' AND $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
     "repeat": "server",
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "measurement": "system_uptime",
       "query": "SELECT mean(\"available_percent\") AS \"value\" FROM \"mem\" WHERE  $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SYSTEM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "system_load1",
       "query": "SELECT mean(load1) as load1,mean(load5) as load5,mean(load15) as load15 FROM \"system\" WHERE $timeFilter GROUP BY time($interval), * ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "mem_inactive",
       "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "SELECT mean(usage_idle) as \"idle\", mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE   cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_path : $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_total",
       "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE  \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk inodes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_path : $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "disk_inodes_free",
       "query": "SELECT mean(inodes_free) as \"free\", mean(inodes_used) as \"used\" FROM \"disk\" WHERE  \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE  \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE  \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE  \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE  \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE  \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host: $tag_name: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "path", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "io_reads",
       "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE  \"name\" =~ /(v|s)d(a|b|c|d)$/ AND $timeFilter GROUP BY time($interval), *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Swap usage (bytes)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT mean(free) as \"free\", mean(used) as \"used\", mean(total) as \"total\" FROM \"swap\" WHERE $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Swap I/O bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT mean(\"in\") as \"in\", mean(\"out\") as \"out\" FROM \"swap\" WHERE $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Swap usage (percent)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "swap_in",
       "query": "SELECT mean(used_percent) as used FROM \"swap\" WHERE $timeFilter GROUP BY time($interval), host ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_method $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select count(*) from http_requests WHERE $timeFilter GROUP BY time($__interval) , method, url",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Error rate (4xx and 5xx)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select count(*) from http_requests where status =~ /^4|5../ and $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Latency (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_method $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean(\"duration\") from http_requests WHERE $timeFilter GROUP BY time($__interval) , method, url",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Avg event loop latency  (ms)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select mean( avg ) from event_loop_latency WHERE $timeFilter  GROUP BY time($interval) ;",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Longest event loop latency (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "max latency",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": " select max(max) from event_loop_latency WHERE $timeFilter  GROUP BY time($__interval) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory heap usage (MB)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "heap",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(used) /1000000 FROM gc WHERE $timeFilter  GROUP BY time($__interval) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC cycle duration (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "duration",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration\") FROM gc WHERE $timeFilter GROUP BY time($__interval) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "NGINX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "Requests / sec." }
     ],
     "targets": [
      {
       "alias": "$tag_host:$tag_port - $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"requests\"),1s) AS \"requests\" FROM \"nginx\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host:$tag_port - $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"handled\"),1s) AS \"handled\" FROM \"nginx\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host:$tag_port - $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"accepts\"),1s) AS \"accepts\" FROM \"nginx\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "Connections / sec." }
     ],
     "targets": [
      {
       "alias": "$tag_host:$tag_port - $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"reading\"),1s) AS \"reading\" FROM \"nginx\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host:$tag_port - $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"writing\"),1s) AS \"writing\" FROM \"nginx\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host:$tag_port - $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"active\"),1s) AS \"active\" FROM \"nginx\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host:$tag_port - $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"waiting\"),1s) AS \"waiting\" FROM \"nginx\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "PHP FPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_url - $tag_pool: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "phpfpm_active_processes",
     "query": "SELECT mean(\"active_processes\") as \"active\",mean(\"idle_processes\") as \"idle\"  FROM \"phpfpm\" WHERE $timeFilter GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accepted connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_url - pool: $tag_pool",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "phpfpm_active_processes",
     "query": "SELECT non_negative_derivative(mean(\"accepted_conn\"),1s) FROM \"phpfpm\" WHERE $timeFilter GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slow requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_url - pool: $tag_pool",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "phpfpm_active_processes",
     "query": "SELECT non_negative_derivative(mean(\"slow_requests\"),1s) FROM \"phpfpm\" WHERE $timeFilter GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max children reached",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_url - pool: $tag_pool",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "phpfpm_active_processes",
     "query": "SELECT mean(\"max_children_reached\") FROM \"phpfpm\" WHERE $timeFilter GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "ElasticSearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "$server",
   "type": "singlestat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "repeat": "server",
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_jvm_uptime_in_millis",
     "query": "SELECT mean(\"uptime_in_millis\") FROM \"elasticsearch_jvm\" WHERE $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Percent usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_os_cpu_idle",
     "query": "SELECT mean(\"cpu_percent\")  FROM \"elasticsearch_process\" WHERE  $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap percent usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_jvm_mem_heap_used_in_bytes",
     "query": "SELECT mean(\"mem_heap_used_percent\")  FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name - $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_jvm_threads_count",
     "query": "SELECT mean(\"threads_count\") AS \"count\", mean(\"threads_peak_count\") AS \"peak count\"  FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name - $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_jvm_mem_heap_committed_in_bytes",
     "query": "SELECT mean(\"mem_heap_max_in_bytes\") AS \"max\", mean(\"mem_heap_commited_in_bytes\") AS \"commited\", mean(\"mem_heap_used_in_bytes\") AS \"used\" FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval),*",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transport size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"rx_size_in_bytes\"), 1s) AS \"rx\" FROM \"elasticsearch_transport\" WHERE  $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"tx_size_in_bytes\"), 1s) AS \"tx\" FROM \"elasticsearch_transport\" WHERE  $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Breakers bytes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fielddata_estimated_size_in_bytes\"), 1s) AS \"fielddata-estimated\" FROM \"elasticsearch_breakers\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"parent_estimated_size_in_bytes\"), 1s) AS \"parent-estimated\" FROM \"elasticsearch_breakers\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fielddata_limit_size_in_bytes\"), 1s) AS \"fielddata-limit\" FROM \"elasticsearch_breakers\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"parent_limit_size_in_bytes\"), 1s) AS \"parent-limit\" FROM \"elasticsearch_breakers\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"request_estimated_size_in_bytes\"), 1s) AS \"request-estimated\" FROM \"elasticsearch_breakers\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"request_limit_size_in_bytes\"), 1s) AS \"request-limit\" FROM \"elasticsearch_breakers\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Breakers",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"fielddata_overhead\") AS \"fielddata-overhead\",mean(\"parent_overhead\") AS \"parent-overhead\", mean(\"request_overhead\") AS \"request-overhead\",mean(\"fielddata_tripped\") AS \"fielddata-tripped\",mean(\"parent_tripped\") AS \"parent-tripped\",mean(\"request_tripped\") AS \"request-tripped\" FROM \"elasticsearch_breakers\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FS Total",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"total_free_in_bytes\") AS \"free\",mean(\"total_available_in_bytes\") AS \"available\",mean(\"total_total_in_bytes\") AS \"total\" FROM \"elasticsearch_fs\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"query_cache_memory_size_in_bytes\") AS \"query-cache\",mean(\"fielddata_memory_size_in_bytes\") AS \"fielddata\",mean(\"request_cache_memory_size_in_bytes\") AS \"request-cache\",mean(\"percolate_memory_size_in_bytes\") AS \"percolate\" FROM \"elasticsearch_indices\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices Merges",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"merges_total_size_in_bytes\") AS \"total\",mean(\"merges_current_size_in_bytes\") AS \"current\" FROM \"elasticsearch_indices\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices Store Size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"store_size_in_bytes\") AS \"store-size\" FROM \"elasticsearch_indices\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices Time operations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(merges_total_time_in_millis) AS \"merges-total\",mean(flush_total_time_in_millis) AS \"flush-total\",mean(get_exists_time_in_millis) AS \"get-exists\",mean(get_missing_time_in_millis) AS \"get-missing\",mean(get_time_in_millis) AS \"get\",mean(indexing_delete_time_in_millis) AS \"indexing-delete\",mean(indexing_index_time_in_millis) AS \"indexing-index\",mean(indexing_throttle_time_in_millis) AS \"indexing-throttle\",mean(merges_total_stopped_time_in_millis) AS \"merges-total-stopped\",mean(merges_total_throttled_time_in_millis) AS \"merges-total-throttled\",mean(merges_total_time_in_millis) AS \"merges-total\",mean(percolate_time_in_millis) AS \"percolate\",mean(recovery_throttle_time_in_millis) AS \"recovery-throttle\",mean(refresh_total_time_in_millis) AS \"refresh-total\",mean(search_fetch_time_in_millis) AS \"search-fetch\",mean(search_query_time_in_millis) AS \"search-query\",mean(search_scroll_time_in_millis) AS \"search-scroll\",mean(store_throttle_time_in_millis) AS \"store-throttle\",mean(suggest_time_in_millis) AS \"suggest\",mean(warmer_total_time_in_millis) AS \"warmer-total\" FROM \"elasticsearch_indices\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices Total Operations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(flush_total) as \"flush\",mean(get_exists_total) as \"get-exists\",mean(get_missing_total) as \"get-missing\",mean(get_total) as \"get\",mean(indexing_delete_total) as \"indexing-delete\",mean(indexing_index_total) as \"indexing-index\",mean(indexing_noop_update_total) as \"indexing-noop-update\",mean(merges_total) as \"merges\",mean(percolate_total) as \"percolate\",mean(refresh_total) as \"refresh\",mean(search_fetch_total) as \"search-fetch\",mean(search_query_total) as \"search-query\",mean(search_scroll_total) as \"search-scroll\",mean(suggest_total) as \"suggest\",mean(warmer_total) as \"warmer\"FROM \"elasticsearch_indices\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices Current Operations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(get_current) as \"get\",mean(indexing_delete_current) as \"indexing-delete\",mean(indexing_index_current) as \"indexing-index\",mean(merges_current) as \"merges\",mean(percolate_current) as \"percolate\",mean(search_fetch_current) as \"search-fetch\",mean(search_query_current) as \"search-query\",mean(search_scroll_current) as \"search-scroll\",mean(suggest_current) as \"suggest\",mean(warmer_current) as \"warmer\" FROM \"elasticsearch_indices\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices query cache counts",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"query_cache_total_count\") AS \"total\",mean(\"query_cache_miss_count\") AS \"miss\",mean(\"query_cache_cache_count\") AS \"cache\",mean(\"query_cache_hit_count\") AS \"hit\" FROM \"elasticsearch_indices\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Indices docs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"docs_count\") AS \"count\",mean(\"docs_deleted\") AS \"deleted\" FROM \"elasticsearch_indices\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Buffer pool mapped",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"buffer_pools_mapped_used_in_bytes\") AS \"used\",mean(\"buffer_pools_mapped_total_capacity_in_bytes\") AS \"total-capacity\" FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Buffer pool direct",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 151 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"buffer_pools_direct_used_in_bytes\") AS \"used\",mean(\"buffer_pools_direct_total_capacity_in_bytes\") AS \"total-capacity\" FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Buffer pool mapped counts",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"buffer_pools_mapped_count\") AS \"count\" FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Buffer pool direct counts",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"buffer_pools_direct_count\") AS \"count\" FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM GC counts",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"gc_collectors_young_collection_count\") AS \"young\",mean(\"gc_collectors_old_collection_count\") AS \"old\" FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"gc_collectors_young_collection_time_in_millis\") AS \"young\",mean(\"gc_collectors_old_collection_time_in_millis\") AS \"old\" FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Memory pool old",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"mem_pools_old_peak_used_in_bytes\") AS \"peak-used\",mean(\"mem_pools_old_peak_max_in_bytes\") AS \"peak-max\",mean(\"mem_pools_old_used_in_bytes\") AS \"used\",mean(\"mem_pools_old_max_in_bytes\") AS \"max\" FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Memory pool young",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 184 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"mem_pools_young_peak_used_in_bytes\") AS \"peak-used\",mean(\"mem_pools_young_peak_max_in_bytes\") AS \"peak-max\",mean(\"mem_pools_young_used_in_bytes\") AS \"used\",mean(\"mem_pools_young_max_in_bytes\") AS \"max\" FROM \"elasticsearch_jvm\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "XA commands",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"commands_xa_commit\")) AS \"commit\" FROM \"mysql\" WHERE $timeFilter GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"commands_xa_end\")) AS \"end\" FROM \"mysql\" WHERE $timeFilter GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"commands_xa_recover\")) AS \"recover\" FROM \"mysql\" WHERE $timeFilter GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"commands_xa_prepare\")) AS \"prepare\" FROM \"mysql\" WHERE $timeFilter GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"commands_xa_rollback\")) AS \"rollback\" FROM \"mysql\" WHERE $timeFilter GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"commands_xa_start\")) AS \"start\" FROM \"mysql\" WHERE $timeFilter GROUP BY time($interval),* fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 195 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT mean(\"open_file_descriptors\") AS \"fd-open\" FROM \"elasticsearch_process\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool bulk",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"bulk_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"bulk_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"bulk_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"bulk_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"bulk_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"bulk_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool refresh",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 206 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"refresh_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"refresh_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"refresh_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"refresh_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"refresh_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"refresh_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool warmer",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"warmer_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"warmer_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"warmer_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"warmer_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"warmer_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool flush",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 217 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"flush_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"flush_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"flush_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"flush_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"flush_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"flush_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool force merge",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 228 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"force_merge_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"force_merge_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"force_merge_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"force_merge_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"force_merge_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"force_merge_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool generic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 228 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"generic_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"generic_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"generic_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"generic_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"generic_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"generic_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool get",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 239 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"get_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"get_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"get_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"get_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"get_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"get_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool index",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 239 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"index_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"index_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"index_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"index_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"index_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"index_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool listener",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 250 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"listener_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"listener_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"listener_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"listener_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"listener_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"listener_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool management",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 250 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"management_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"management_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"management_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"management_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"management_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"management_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool suggest",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 261 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"suggest_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"suggest_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"suggest_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"suggest_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"suggest_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"suggest_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool snapshot",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 261 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"snapshot_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"snapshot_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"snapshot_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"snapshot_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"snapshot_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"snapshot_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool optimize",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 272 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $m",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"value\")) AS \"value\" FROM /elasticsearch_thread_pool_optimize.*/ WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool search",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 272 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"search_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"search_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"search_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"search_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"search_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"search_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool percolate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 283 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"percolate_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"percolate_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"percolate_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"percolate_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"percolate_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"percolate_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool fetch shard started",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 283 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_started_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_started_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_started_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_started_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_started_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_started_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool fetch shard store",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 294 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_store_completed\")) AS \"completed\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_store_threads\")) AS \"threads\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_store_rejected\")) AS \"rejected\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_store_queue\")) AS \"queue\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_store_largest\")) AS \"largest\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_node_name: $col",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "elasticsearch_transport_rx_count",
     "query": "SELECT non_negative_derivative(mean(\"fetch_shard_store_active\")) AS \"active\" FROM \"elasticsearch_thread_pool\" WHERE  $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mongo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 305 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host:$tag_state $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "measurement": "mongodb_commands_per_sec",
       "query": "SELECT mean(\"open_connections\") AS \"open-connections\" FROM \"mongodb\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Net",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host:$tag_state $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "measurement": "mongodb_commands_per_sec",
       "query": "SELECT mean(\"net_in_bytes\") AS \"in\",mean(\"net_out_bytes\") AS \"out\" FROM \"mongodb\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Commands",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host:$tag_state $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "measurement": "mongodb_commands_per_sec",
       "query": "SELECT mean(\"commands_per_sec\") AS \"commands\",mean(\"deletes_per_sec\") AS \"deletes\",mean(\"flushes_per_sec\") AS \"flushes\",mean(\"getmores_per_sec\") AS \"getmores\",mean(\"inserts_per_sec\") AS \"inserts\",mean(\"updates_per_sec\") AS \"updates\" FROM \"mongodb\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Mongodb Active",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host:$tag_state $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "state", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "mongodb_active_reads",
       "query": "SELECT mean(\"active_reads\") as \"reads\",mean(\"active_writes\") as \"writes\" FROM \"mongodb\" WHERE  $timeFilter GROUP BY time($interval), \"host\", \"state\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host:$tag_state $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "measurement": "mongodb_commands_per_sec",
       "query": "SELECT mean(\"mapped_megabytes\") AS \"mapped\",mean(\"non-mapped_megabytes\") AS \"non-mapped\",mean(\"resident_megabytes\") AS \"resident\",mean(\"vsize_megabytes\") AS \"vsize\" FROM \"mongodb\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Queue",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host:$tag_state $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "measurement": "mongodb_commands_per_sec",
       "query": "SELECT mean(\"queued_reads\") AS \"reads\",mean(\"queued_writes\") AS \"writes\" FROM \"mongodb\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "ReplicaSet Commands",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host:$tag_state $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "measurement": "mongodb_commands_per_sec",
       "query": "SELECT mean(\"repl_commands_per_sec\") AS \"commands\",mean(\"repl_deletes_per_sec\") AS \"deletes\",mean(\"repl_getmores_per_sec\") AS \"getmores\",mean(\"repl_inserts_per_sec\") AS \"inserts\",mean(\"repl_queries_per_sec\") AS \"queries\",mean(\"repl_updates_per_sec\") AS \"updates\" FROM \"mongodb\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Page Faults",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host:$tag_state $col",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" }
       ],
       "measurement": "mongodb_commands_per_sec",
       "query": "SELECT mean(\"page_faults_per_sec\") AS \"page-faults\" FROM \"mongodb\" WHERE  $timeFilter GROUP BY time($interval),*",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "DOCKER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 306 } },
  {
   "title": "Running containers by Host",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 307 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"container_id\")) FROM \"docker_container_cpu\" WHERE $timeFilter GROUP BY host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Containers by Host",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 307 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"n_containers\") FROM \"docker\" WHERE $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GO Routines by host",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 307 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"n_goroutines\") FROM \"docker\" WHERE $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "File Descriptors by host",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 307 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"n_used_file_descriptors\") FROM \"docker\" WHERE $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total CPUs per Host",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 314 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"n_cpus\") FROM \"docker\" WHERE $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM per host",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 314 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"memory_total\") FROM \"docker\" WHERE $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Images per host",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 314 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"n_images\") FROM \"docker\" WHERE $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU usage by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 321 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "query": "SELECT mean(\"usage_percent\") as \"usage\" FROM \"docker_container_cpu\" WHERE $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM usage by container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 329 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "query": "SELECT mean(\"usage_percent\") as \"usage\" FROM \"docker_container_mem\" WHERE $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network usage by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 337 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_bytes\"),1s)/8 as \"rx\" FROM \"docker_container_net\" WHERE  $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_bytes\"),1s)/8 as \"tx\" FROM \"docker_container_net\" WHERE  $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network packets by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 345 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_packets\"),1s) as \"rx\" FROM \"docker_container_net\" WHERE  $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_packets\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network dropped by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 353 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_dropped\"),1s) as \"rx\" FROM \"docker_container_net\" WHERE  $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_dropped\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network errors by container / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 361 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"rx_errors\"),1s) as \"rx\" FROM \"docker_container_net\" WHERE  $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: $tag_container_image: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "query": "SELECT non_negative_derivative(mean(\"tx_errors\"),1s) as \"tx\" FROM \"docker_container_net\" WHERE  $timeFilter GROUP BY time($interval),* fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}